sudo: false

# only one TRAVIS_PYTHON_VERSION
language: python
python:
  - 2.7

# matrix of several CONDA_PYTHON_VERSIONs
env:
  matrix:
    - CONDA_PYTHON_VERSION=2.7.9
    - CONDA_PYTHON_VERSION=2.7.13
    # Python 3 not supported yet
    #- CONDA_PYTHON_VERSION=3.5
    #- CONDA_PYTHON_VERSION=3.4
    #- CONDA_PYTHON_VERSION=3.3

addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran

before_install:
  # get miniconda
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O $HOME/miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O $HOME/miniconda.sh;
    fi
  # install miniconda in batch mode and add to PATH
  - bash $HOME/miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"

  # configure conda for batch mode
  - conda config --set always_yes yes --set changeps1 no
  # update conda and show package/environment information
  - conda update -q conda
  - conda info -a

  # install some dependencies with conda and activate environment
  - conda create -q -n kafe_env python=$CONDA_PYTHON_VERSION numpy scipy tk matplotlib
  - source activate kafe_env

  # upgrade pip to latest version and install dependencies with pip
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install --upgrade iminuit
  - pip install --upgrade numdifftools
  - pip install --upgrade yaml

  # output python version to log
  - python --version

install:
  # install kafe from current directory using pip
  - pip install -e .

script:
  # run unittests with setup.py
  - python setup.py test
